### PR TITLE
Replace bcrypt with jasypt strong password encryption

### PR DESCRIPTION
**Pull request by hlbraddock**
@frett In order to support legacy Relay security answer hashes.

### CODE REVIEW

**Comment by frett** [comment]
since we are importing legacy hashes, we will probably need to deal with checking the SA however it was originally checked bypassing normalization.

We may want to move the string normalization into the HashUtility class, so it locally checks the raw answer along with a normalized answer.

**Comment by hlbraddock** [comment]
Hmmm... possibly so. I made these changes before reading your comment.

**Comment by hlbraddock** [comment]
I'm inclined to want to leave `HashUtility` simplistic.

**Comment by frett** [comment]
k, that's fine, I'm making sure I have the jira task to implement a recovery email address created and assigned to the planned version after we are fully merged. I really don't want to support SQ/SA long term at all :)

**Comment by frett** [comment]
looks good, +1

**Comment by hlbraddock** [comment]
I agree. I have wanted to retire SQSA for a long time, and would've probably done so but for Google users.

**Pull request merged**
