### PR TITLE
Allow for more granular update of Cru person attributes.

### PR DESCRIPTION
**Pull request by hlbraddock**

### CODE REVIEW

**Comment by hlbraddock** [comment]
@frett

**Comment by hlbraddock** [comment]
@frett I can make changes to the schema in test (adding all the attributes to relayAttributes object class), but if you've already made a copy for production, we'll need to manually add them there as well.

**Comment by frett** [comment]
yeah, I'll get them added to production

**Comment by frett** [comment]
looks good +1

I need to double check our user objects, but we may be able to remove ```LDAP_ATTR_OBJECTCLASS``` from all the attribute groups

**Pull request merged**
