### PR TITLE
retry failed move operations

### PR DESCRIPTION
**Pull request by frett**

### CODE REVIEW

**Comment by frett** [comment]
@hlbraddock 

here is the move failure retry logic.

I removed synchronization completely because it made a large performance difference (1:40 vs 9:30) when running it from home on 1000 accounts. Internally there are more errors thrown, but all of the requests generating those errors are retried internally and the calling code is none the wiser. The performance difference is due to the fact that with synchronization you are serializing the latency of every modifyDn request the code issues.

**Comment by hlbraddock** [comment]
'Nice' result code from partition busy exception. Is 100 milliseconds sufficient wait time?

Other than that, this is a nice refactor, for performance improvement and handling of the partition busy exception.

+1

**Comment by hlbraddock** [comment]
This is also my second code review including `Future`s, which I appreciate seeing the use of.

**Comment by frett** [comment]
it's recursive and keeps retrying until it succeeds or gets a different response. From what I can tell eDirectory is only locked briefly (e.g. it's only locked during the time it takes a modifyDn operation to complete, which is much less than 100ms). I'm not sure about the other cases that cause the partition to be locked. But because I'm not using a retry limit and just recursing indefinitely* (until it runs out of stack space) I didn't want it waiting a long time to continue on.

**Comment by frett** [comment]
this is my first time using `Future`s in java. I've used the concept of them before in several perl scripts to handle highly concurrent operations using a non-blocking event loop (they weren't called futures, but I used `$task->join` which is the same concept of accessing the finished results of a thread running).

I ended up using them this time so I could propagate Exceptions out of the multi-threaded executor to the main thread. I left me test code in there but disabled just in case it was needed for more testing down the line.

**Pull request merged**
